
development:
  adapter: postgresql
  encoding: unicode
  database: comuna_development
  pool: 5
  username: postgres
  password: postgres
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: comuna_test
  pool: 5
  username: postgres
  password: postgres
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: comuna_production
  pool: 5
  username: postgres
  password: postgres
  host: localhost
